# Generated by Django 5.2.1 on 2025-05-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreenEase', '0003_alter_resume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
