# Generated by Django 5.2.1 on 2025-05-29 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreenEase', '0004_uploadedresume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='uploadedresume',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(unique=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='uploadedresume',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
