# Generated by Django 5.2.1 on 2025-05-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreenEase', '0005_delete_user_resume_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploadedresume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploadedresume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
