# Generated by Django 5.2.1 on 2025-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreenEase', '0006_alter_resume_created_at_alter_resume_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadedresume',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='work',
            field=models.TextField(null=True),
        ),
    ]
